"""
Author: Edgar Zamora Gomez  <edgar.zamora@urv.cat>
"""

METHOD = 'method'
PARAMS = 'params'
SRC = 'src'
AREF = 'aref'
CLS = 'cls'
HOSTNAME = 'hostname'
MODE = 'mode'
ONEWAY = 'oneway'
SYNC = 'sync'
TYPE = 'type'
CALL = 'call'
RESULT = 'result'
RPC_ID = 'rpc_id'
TIMEOUT = 'timeout'
RPC = 'rpc'
FROM = 'from'
TO = 'to'
TIMEOUT = 'timeout'
ERROR = 'error'
MULTI = 'multi'
TCP = 'tcp'
HTTP = 'http'
TARGET = 'target'
TCP = 'tcp'
MOM = 'mom'
IP = 'ip'
PORT = 'port'
NAMESPACE = 'namespace'
NAME = 'name'
ATOM = 'atom'
REF = 'ref'
